//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace keap_rest_hooks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessToken
    {
        public int id { get; set; }
        public string client_id { get; set; }
        public string access_token { get; set; }
    }
}
